version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:905418302596:task-definition/kartik:2"
        LoadBalancerInfo:
          ContainerName: "kartik"
          ContainerPort: 5000

# Speed up Blue-Green Deployment
deploymentOption: WITH_TRAFFIC_CONTROL
terminationWaitTimeInMinutes: 1  # Reduce wait time from 30 min to 1 min
deploymentConfiguration:
  type: ALL_AT_ONCE  # Instantly shift 100% traffic to new tasks

